config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root "welcome#index"
  
  # Add web pages bellow
  get 'admin-panel', to: "admin_panel#index"
  get 'list-users', to: "admin_panel#list_users"
  get 'add-article', to: "admin_panel#add_article"
  get 'about', to: 'pages#about'
  get 'contact', to: "pages#contact"
  # Add resources bellow
  resources :users
  resources :articles
  resources :categories
  resources :ads
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # get 'login', to: "users#sign_in"
  # get 'signup', to: "users#sign_up"
  # get 'adminlogin', to: "admins#sign_in"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10}
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  # attr_accessor :featured
  has_attached_file :featured,
  storage: :dropbox,
  dropbox_credentials: Rails.root.join("config/dropbox.yml"),
  styles: {full: "1366x768" ,featured:"1024x768#", medium: "300x300#", thumb: "100x100#"},    
  dropbox_options: {      
  path: proc{|style| "#{style}/#{id}_#{featured.original_filename}"},  
  unique_filename: true  
  }
  validates_attachment_content_type :featured, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :category

  
  def index
    @article = Article.all.order("created_at desc")
    @ad = Ad.all.order("created_at desc").limit(3)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article, notice: "Your article was successfully saved!"
    else
      render 'new', notice: "Your article could not be saved!"
    end
  end
  
  def show
    @ad = Ad.all.order("created_at desc").limit(3)
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "This article was successfully updated"
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article Deleted Successfully"
    redirect_to articles_path
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :description, :featured, category_ids: [])
  end
  
  def find_article
     @article = Article.find(params[:id]) 
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <section class="news">
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <div class="panel panel-info">
            <%= image_tag article.featured.url(:medium), class: "img-responsive" %>
            <div class="panel-body">
              <h4><%= truncate(article.title, length: 25) %></h4>
              <p><%= article.created_at.strftime("%B %d, %Y") %></p>
              <p><%= truncate(article.description, length: 100) %></p>
              <%= link_to "Read More", article_path(article) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/articles/_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 15, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :featured %>
        </div>
        <div class="col-sm-8">
          <%= f.file_field :featured %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-5 col-sm-offset-2">
            <p>Categories: </p>
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container-fluid padding-bottom">
  <section class="form">
    <h1 align="center">Edit this article</h1>
    <%= render "form" %>
  </section>
</div>

app/views/articles/index.html.erb
<div class="container-fluid">

  
<section class="news-articles padding-top">
  <div class="container">
    <div class="row">
      <% @article.in_groups_of(4, false).each do |group|%>
        <div class= "main col-xs-3 padding-top">
          <% group.each do |article| %>
            <div class="container-fluid container-white-color padding-top">
              <div class="overlay">
                <%= image_tag article.featured.url(:featured), class: "img-responsive" %>
                <div class="caption">
                  <%= link_to truncate(article.title, length: 25), article_path(article)%>
                </div>
              </div>
            </div>
            <div class="container-fluid container-white-color">
              
              <p><%= article.created_at.strftime("%B %d, %Y") %></p>
              <p><%= truncate(article.description, length: 50) %></p>
              <%= link_to "Read More", article_path(article) %>
            </div>
            <br>
          <% end %>
        </div>
      <% end %>
      <div class="sidebar col-xs-3">
        <%= render 'layouts/ads' %>
      </div>
    </div>
  </div>
</section>
  
  
</div>

app/views/articles/new.html.erb
<div class="container-fluid padding-bottom">
  <section class="form">
    <h1 align="center">Create a new article</h1>
    <%= render "form" %>
  </section>
</div>

app/views/articles/show.html.erb
<div class="container-fluid padding-top">
  <div class="row">
    <div class="col-xs-9">
      <div class="container-fluid container-white-color">
        <h1 align="center"><%= @article.title %></h1>
        <% if @article.categories.any? %>
          <% @article.categories.each do |category| %>
            <li class="list-unstyled badge"><%= render category %></li>
          <% end %>
        <% end %>
        <hr>
          <p><span class="fa fa-clock-o"></span> <%= @article.created_at.strftime('%A, %B, %d') %></p>
        <hr>
      </div>

      <div class="container-fluid container-white-color">
         <%= image_tag @article.featured.url(:featured), class: "img-responsive thumbnail" %>
      </div>
      <div class="container-fluid container-white-color">
        <p><%= simple_format(@article.description) %></p>
      </div>
     
      <div class="container-fluid container-white-color padding-bottom">
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-small btn-primary"  %>
        <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-danger btn-small" %>
      </div>
    </div>
    <div class="col-xs-3">
      <%= render 'layouts/ads' %>
    </div>
  </div>

</div>

    
    