config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root "welcome#index"
  
  # Add web pages bellow
  get 'admin-panel', to: "admin_panel#index"
  get 'list-users', to: "admin_panel#list_users"
  get 'add-article', to: "admin_panel#add_article"
  get 'about', to: 'pages#about'
  get 'contact', to: "pages#contact"
  # Add resources bellow
  resources :users
  resources :articles
  resources :categories
  resources :ads
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # get 'login', to: "users#sign_in"
  # get 'signup', to: "users#sign_up"
  # get 'adminlogin', to: "admins#sign_in"
  
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  
  before_action :category
  
  def index
    
  end
  
  def list_users
    
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/index.html.erb
 <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= Article.count %></div>
                                    <div>Total Articles Created</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left"><%= link_to "Show All Articles", 'articles' %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= Category.count %></div>
                                    <div>Categories Created</div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <span class="pull-left"><%= link_to "View All Categories", 'category' %></span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= Ad.count %></div>
                                    <div>Ads Created</div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <span class="pull-left"><%= link_to "View All Ads", 'ad' %></span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Notifications Panel
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-comment fa-fw"></i> Total News So far
                                    <span class="pull-right text-muted small"><em><%= Article.count %> Articles</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-twitter fa-fw"></i> Latest News
                                    <span class="pull-right text-muted small"><em><%= Article.last.created_at.strftime("%B %d, %Y") %></em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-envelope fa-fw"></i> Categories Created
                                    <span class="pull-right text-muted small"><em><%= Category.count %></em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-envelope fa-fw"></i> Categories Created
                                    <span class="pull-right text-muted small"><em><%= Article.last.created_at.strftime("%B %d, %Y") %></em>
                                    </span>
                                </a>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                    <div class="col-lg 12">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <i class="fa fa-gear panel-title">&nbsp;Controls</i> 
                                </div>
                                    <div class="panel-body">
                                        <div class="col-lg-4 ">
                                            <div class="btn btn-primary ck-controls"><%= link_to "Create Author User", new_user_path %></div>
                                        </div>
                                        <div class="col-lg-4 ">    
                                            <div class="btn btn-warning ck-controls"><%= link_to "Add New Articles", new_article_path %></div>
                                        </div>
                                        <div class="col-lg-4 ">
                                            <div class="btn btn-success ck-controls"><%= link_to "Create new advertisements", new_ad_path %></div>
                                        </div>
                                    </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->