config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root "welcome#index"
  
  # Add web pages bellow
  get 'admin-panel', to: "admin_panel#index"
  get 'list-users', to: "admin_panel#list_users"
  get 'add-article', to: "admin_panel#add_article"
  get 'about', to: 'pages#about'
  get 'contact', to: "pages#contact"
  # Add resources bellow
  resources :users
  resources :articles
  resources :categories
  resources :ads
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # get 'login', to: "users#sign_in"
  # get 'signup', to: "users#sign_up"
  # get 'adminlogin', to: "admins#sign_in"
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :category
  
  def index
    @ad = Ad.all.order("created_at desc").limit(3)
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles
    @ad = Ad.all.order("created_at desc").limit(3)
  end
  
  def destroy
    @category.destroy
    redirect_to categories_path
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span><%= link_to category.name, category_path(category), class: "article-category badge" %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<div class="container-fluid padding-bottom">
  <section class="edit-category">
    <h1 align="center">Edit category</h1>
    <%= render "form" %>
  </section>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="container-fluid padding-bottom">
  <section class="edit-category">
    <h1 align="center">Create a new category</h1>
    <%= render "form" %>
  </section>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
  <% if can? :all, @category %>
    <div align="center">
        <div class="row">
          <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
        </div>
    </div>
  <% end %>
  <section class="news-articles padding-top">
    <div class="container-fluid">
      <div class="row">
        <% @category_articles.in_groups_of(3, false).each do |art|%>
          <div class= "main col-xs-4">
            <% art.each do |article| %>
              <div class="container-fluid container-white-color padding-top">
                <div id="box">
                  <%= image_tag article.featured.url(:medium), class: "img-responsive" %>
                  <div id="overlay">
                    <div id="caption">
                      <%= link_to truncate(article.title, length: 25), article_path(article)%>
                    </div>
                  </div>    
                </div>
              </div>
              <div class="container-fluid container-white-color">
                <p><%= article.created_at.strftime("%B %d, %Y") %></p>
                <p><%= truncate(article.description, length: 50) %></p>
                <%= link_to "Read More", article_path(article) %>
              </div>
              <br>
            <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </section>

</div>