config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root "welcome#index"
  
  # Add web pages bellow
  get 'admin-panel', to: "admin_panel#index"
  get 'list-users', to: "admin_panel#list_users"
  get 'add-article', to: "admin_panel#add_article"
  get 'about', to: 'pages#about'
  get 'contact', to: "pages#contact"
  # Add resources bellow
  resources :users
  resources :articles
  resources :categories
  resources :ads
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # get 'login', to: "users#sign_in"
  # get 'signup', to: "users#sign_up"
  # get 'adminlogin', to: "admins#sign_in"
  
end

app/views/layouts/_admin_nav.html.erb
<!--Navigation-->
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to admin_panel_path, class: "navbar-brand ck-admin-brand" do %>
        <i class="fa fa-tachometer"></i> Admin Panel
    <% end %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-newspaper-o"></i> Articles <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to new_article_path do %>
                <i class="fa fa-plus"></i> Add New Article
              <% end %>
            </li>
            <li>
              <%= link_to new_category_path do %>
                <i class="fa fa-tag"></i> Add New Category
              <%end %>
            </li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-users"></i> Users<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "" do %>
                <i class="fa fa-user-plus"></i> Add Author
              <% end %>
            </li>
            <li>
              <%= link_to "" do %>
                <i class="fa fa-user-plus"></i> Add Members
              <% end %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-money"></i> Advertisements<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to new_ad_path do %>
                <i class="fa fa-plus"></i> Add Advertisement
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> Admin User<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to root_path do %> 
                Main website <i class="fa fa-arrow-circle-right"></i>
              <% end %>
            </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header"><i class="fa fa-cogs"></i> Settings</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_ads.html.erb
<p class="titelize text-right">Advertisements</p>
<% @ad.in_groups_of(2, false).each do |ad| %> 
  <% ad.each do |ads| %>
    <%= link_to "#{image_tag (ads.image.url(:medium))}".html_safe, ads.url, class: "img-responsive advertisement" %>
    <br>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="big-footer">
  <div class="container sub-footer">
    <div class="row">
      <div class="col-xs-3">
        <h4 class="footer-section-titles">
          Top News
        </h4>
        <li class="list-unstyled">
          <!--here we will loop through latest news descending (links only)-->
          <%# @articles.each do |article| %>
            <%#= link_to article.title %>
          <%# end %>
        </li>
      </div>
      <div class="col-xs-3">
        <h4 class="footer-section-titles">
          <!--cultural activities-->
          Cultural activities
        </h4>
        <li class="list-unstyled">
          
        </li>
      </div>
      <div class="col-xs-3">
        <h4 class="footer-section-titles">
          Advertisements
        </h4>
        <li class="list-unstyled">
          
        </li>
      </div>
      <div class="col-xs-3">
        <h4 class="footer-section-titles">
          Connect With Us
        </h4>
        <li class="list-unstyled">
          <i class="fa fa-twitter"></i>
        </li>
        <li class="list-unstyled">
          <i class="fa fa-facebook"></i>
        </li>
        <li class="list-unstyled">
          <i class="fa fa-instagram"></i>
        </li>
        <li class="list-unstyled">
          <i class="fa fa-whatsapp"></i>
        </li>
      </div>
    </div>
  </div>
  <p class="text-center copyright text-muted"><%= link_to "Revakhand Today", root_path %> All Rights Reserved &copy; <%= Time.now.year %></p>
  <p class="text-center developers text-muted">Made with <i class="fa fa-coffee"></i> &amp; <i class="fa fa-heart"></i> By <%= link_to "CodeKrieg", "http://codekrieg.com" %> - A RoR Development Company</p>
</footer>

app/views/layouts/_nav.html.erb
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("logo.png"), root_path, class: "navbar-brand img-responsive") %>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Latest Articles", articles_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
         
          <% if can? :manage, :all %>
            <li><%= link_to "Admin Dashboard", admin_panel_path %></li>
          <% end %>
            
            
             <% if logged_in? %>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
             <% end %>
        </ul>
      </div>
    </div>
    <div class="container-fluid">
    <div class="navbar subnav" role="navigation">
      <div class="navbar-inner">
        	<li class= "list-unstyled">
        	  <% @categories.each do |category| %>
        	    <%= link_to "#{category.name}", category_path(category) %>
        	  <% end %>
        	</li>
      </div>
    </div>
  </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NewsApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <% if current_page?('/admin-panel') || current_page?('/list-users') %>
      <%= render 'layouts/admin_nav' %>
    <% else %>
      <%= render 'layouts/nav' %>
    <% end %>
    
    <div class="container page-content">
          <%= bootstrap_flash %>
          <%= yield %>
    </div> <!-- /container -->
    <%= render "layouts/footer" %>
  </body>
</html>